name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: [latest]
        ios-version: [latest]
        device: [iPhone 15]

    env:
      XCODE_PROJECT: ScanApp.xcodeproj
      XCODE_SCHEME: ScanApp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project ${{ env.XCODE_PROJECT }}

      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild clean build test \
            -project ${{ env.XCODE_PROJECT }} \
            -scheme ${{ env.XCODE_SCHEME }} \
            -destination "platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios-version }}" \
            -configuration Debug \
            -enableCodeCoverage YES | tee xcodebuild.log | xcpretty --test --color --report junit --output build/reports/tests/test-results.xml

      - name: Confirm xcodebuild.log Generation
        run: |
          if [ -f xcodebuild.log ]; then
            echo "xcodebuild.log file generated successfully."
          else
            echo "xcodebuild.log file not found."
          fi

      - name: Print Entire xcodebuild Log
        if: always()
        run: |
          echo "Printing the entire xcodebuild log for debugging:"
          cat xcodebuild.log

      - name: Extract Test Case Passed Count
        if: always()
        run: |
          if [ -f xcodebuild.log ]; then
            TEST_CASES_PASSED=$(grep -o 'Test Case.*passed' xcodebuild.log | wc -l)
            echo "Test Cases Passed: $TEST_CASES_PASSED"
          else
            echo "xcodebuild.log file not found."
          fi

      - name: Extract Test Coverage
        if: always()
        run: |
          if [ -f xcodebuild.log ]; then
            TEST_COVERAGE=$(grep -o 'Test coverage.*' xcodebuild.log)
            echo "Test Coverage: $TEST_COVERAGE"
          else
            echo "xcodebuild.log file not found."
          fi

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            ~/Library/Developer/Xcode/DerivedData/ScanApp*/Logs/Test/*.xcresult
            build/reports/tests/test-results.xml

      - name: Display Test Results Summary
        if: always()
        run: |
          echo "Test Results Summary:"
          if [ -f build/reports/tests/test-results.xml ]; then
            grep "<testsuite " build/reports/tests/test-results.xml
          else
            echo "Test results XML file not found."
          fi
