name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest
    strategy:
      matrix:
        xcode-version: [latest]
        ios-version: [latest]
        device: [iPhone 15]

    env:
      XCODE_PROJECT: ScanApp.xcodeproj
      XCODE_SCHEME: ScanApp

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Install xcpretty
        run: |
          gem install xcpretty

      - name: Add Dummy Provisioning Profile
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp .github/provisioning/dummy.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Set Up Code Signing Identity
        run: |
          security create-keychain -p actions temp.keychain
          security default-keychain -s temp.keychain
          security unlock-keychain -p actions temp.keychain
          security set-keychain-settings -t 3600 -u temp.keychain

      - name: Resolve Swift Package Dependencies
        run: xcodebuild -resolvePackageDependencies -project ${{ env.XCODE_PROJECT }}

      - name: Build and Test
        run: |
          set -o pipefail && xcodebuild clean build test \
            -project ${{ env.XCODE_PROJECT }} \
            -scheme ${{ env.XCODE_SCHEME }} \
            -destination "platform=iOS Simulator,name=${{ matrix.device }},OS=${{ matrix.ios-version }}" \
            -configuration Debug \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            PROVISIONING_PROFILE_SPECIFIER="" \
            -enableCodeCoverage YES | xcpretty --test --color

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            ~/Library/Developer/Xcode/DerivedData/ScanApp*/Logs/Test/*.xcresult

      - name: Display Test Results
        if: always()
        run: |
          xcpretty -r json-compilation-database -o build/reports/tests/test-results.json
          cat build/reports/tests/test-results.json
