name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      XCODE_PROJECT: ScanApp.xcodeproj
      XCODE_SCHEME: ScanApp
      TEST_TARGET: NetWork
      SWIFT_PACKAGE_FRAMEWORK: NetWork

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Resolve Swift Package Dependencies
        run: |
          xcodebuild -resolvePackageDependencies -project ${{ env.XCODE_PROJECT }}

      - name: Build and test
        run: |
          xcodebuild clean build test \
            -project ${{ env.XCODE_PROJECT }} \
            -scheme ${{ env.XCODE_SCHEME }} \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -only-testing: "${{ env.SWIFT_PACKAGE_FRAMEWORK }}" \
            -enableCodeCoverage YES
