name: iOS Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    env:
      XCODE_PROJECT: ScanApp.xcodeproj
      XCODE_SCHEME: ScanApp

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest

    - name: Build and test
      run: |
        xcodebuild clean build test \
          -project $XCODE_PROJECT \
          -scheme $XCODE_SCHEME \
          -destination 'platform=iOS Simulator,name=iPhone 12,OS=latest' \
          -enableCodeCoverage YES | xcpretty
